### ISSUE TITLE
source repository not available anymore

### ISSUE THREAD

**Issue by BuckarooBanzay** [minetest-mirrors/playerfactions#1]
@katp32 your new redirect to the `playerfactions` mod is not a git repository from the looks of it:
https://leagueh.xyz/git/katp32/playerfactions/

In the case you abandoned that mod: can you update your forum post and move the source somewhere public please?
Also: you can consider moving it to the `minetest-mods` organization, thanks :+1:

**Comment by crabctrl** [comment]
The repository can be cloned with the URL `https://leagueh.xyz/git/katp32/playerfactions/.git`. See the post on Minetest Forums for more detail.
